FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    xvfb \
    x11-apps \
    libgl1-mesa-glx \
    && pip install pybullet \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY carrito.py .

CMD ["python", "carrito.py"]
