FROM python:3.10-slim

# Instalar dependencias necesarias para PyBullet y entorno gráfico
RUN apt-get update && apt-get install -y \
    xvfb \
    x11-apps \
    libgl1 \
    && pip install pybullet \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY volador.py .

CMD ["python", "volador.py"]
